# Generated by Django 5.2 on 2025-06-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_vetclinicuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_patient',
            new_name='is_vetworker',
        ),
    ]
