# Generated by Django 5.2 on 2025-06-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_is_patient_customuser_is_vetworker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VetClinicUser',
            new_name='VetWorkerUser',
        ),
    ]
