# Generated by Django 5.2 on 2025-06-18 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_vetclinicuser_vetworkeruser'),
        ('vetclinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetworkeruser',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='vetclinic.veterinaryclinic'),
            preserve_default=False,
        ),
    ]
